# Generated by Django 2.0.1 on 2018-02-27 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=7)),
                ('rank', models.CharField(max_length=5)),
                ('price_usd', models.FloatField(max_length=20)),
                ('volume_24h_usd', models.CharField(max_length=20)),
                ('market_cap_usd', models.CharField(max_length=20)),
                ('available_supply', models.CharField(max_length=20)),
                ('total_supply', models.CharField(max_length=20)),
                ('percent_change_1h', models.CharField(max_length=10)),
                ('percent_change_24h', models.CharField(max_length=10)),
                ('percent_change_7d', models.CharField(max_length=10)),
                ('last_updated', models.CharField(max_length=20)),
                ('ticker_history', models.CharField(default='', max_length=44)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.BooleanField(default=True)),
                ('subscription_status', models.BooleanField(default=True)),
                ('alerts', models.ManyToManyField(default='', related_name='user_alerts', to='api.Currency')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(default='', related_name='user_watchlist', to='api.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='coinalert',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Currency'),
        ),
    ]
