# Generated by Django 2.0.1 on 2018-03-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='max_supply',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
