# Generated by Django 2.0.1 on 2018-01-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='player1',
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.CharField(default='ale', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(default='ale', max_length=20),
            preserve_default=False,
        ),
    ]
