# Generated by Django 2.0.1 on 2018-01-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180122_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('symbol', models.CharField(max_length=7)),
                ('price_usd', models.FloatField(max_length=20)),
                ('percent_change_1h', models.FloatField(max_length=20)),
                ('percent_change_24h', models.FloatField(max_length=20)),
                ('alert', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=7)),
                ('rank', models.CharField(max_length=5)),
                ('price_usd', models.FloatField(max_length=20)),
                ('volume_24h_usd', models.CharField(max_length=20)),
                ('market_cap_usd', models.CharField(max_length=20)),
                ('available_supply', models.CharField(max_length=20)),
                ('total_supply', models.CharField(max_length=20)),
                ('percent_change_1h', models.CharField(max_length=20)),
                ('percent_change_24h', models.CharField(max_length=20)),
                ('percent_change_7d', models.CharField(max_length=20)),
                ('last_updated', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=7)),
                ('rank', models.CharField(max_length=5)),
                ('price_usd', models.CharField(max_length=20)),
                ('volume_24h_usd', models.CharField(max_length=20)),
                ('market_cap_usd', models.CharField(max_length=20)),
                ('available_supply', models.CharField(max_length=20)),
                ('total_supply', models.CharField(max_length=20)),
                ('percent_change_1h', models.CharField(max_length=20)),
                ('percent_change_24h', models.CharField(max_length=20)),
                ('percent_change_7d', models.CharField(max_length=20)),
                ('last_updated', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
