# Generated by Django 2.0.1 on 2018-01-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180127_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.BooleanField(default=True)),
                ('subscription_status', models.BooleanField(default=False)),
            ],
        ),
    ]
