# Generated by Django 2.0.1 on 2018-01-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_extenduser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='percent_change_1h',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='price_usd',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert',
            field=models.CharField(max_length=40),
        ),
    ]
