# Generated by Django 2.0.1 on 2018-01-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_currency_ticker_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_id',
        ),
        migrations.AddField(
            model_name='alert',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Currency'),
        ),
    ]
