# Generated by Django 2.0.1 on 2018-02-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180130_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchlist',
            name='available_supply',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='market_cap_usd',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='percent_change_1h',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='total_supply',
        ),
        migrations.RemoveField(
            model_name='userwatchlist',
            name='volume_24h_usd',
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='user_id',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='watchlist',
            field=models.TextField(default=''),
        ),
    ]
