# Generated by Django 2.0.1 on 2018-02-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180202_0424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWatchlist',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='watchlist',
            field=models.ManyToManyField(to='api.Currency'),
        ),
    ]
