# Generated by Django 2.0.1 on 2018-02-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180203_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='watchlist',
            field=models.ManyToManyField(default='', to='api.Currency'),
        ),
    ]
