# Generated by Django 2.0.1 on 2018-02-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180203_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='email_contact',
            field=models.BooleanField(default=False),
        ),
    ]
