# Generated by Django 2.0.1 on 2018-02-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180203_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='email_contact',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='subscription_status',
        ),
    ]
