# Generated by Django 2.0.1 on 2018-02-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180203_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='subscription_status',
            field=models.BooleanField(),
        ),
    ]
