# Generated by Django 2.0.1 on 2018-02-04 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20180203_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='percent_change_1h',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='percent_change_24h',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='percent_change_7d',
            field=models.CharField(max_length=10),
        ),
    ]
