# Generated by Django 2.0.1 on 2018-02-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180204_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
