# Generated by Django 2.0.1 on 2018-02-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180204_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='alerts',
            field=models.ManyToManyField(default='', related_name='user_alerts', to='api.Currency'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='watchlist',
            field=models.ManyToManyField(default='', related_name='user_watchlist', to='api.Currency'),
        ),
    ]
