# Generated by Django 2.0.1 on 2018-02-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180208_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='subscription_status',
            field=models.BooleanField(default=True),
        ),
    ]
