# Generated by Django 2.0.1 on 2018-02-15 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180208_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='date_joined',
            field=models.TimeField(default=datetime.date(2018, 2, 15)),
        ),
    ]
