# Generated by Django 2.0.1 on 2018-02-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_extenduser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='date_joined',
            field=models.TimeField(default='2018-02-15'),
        ),
    ]
